### ISSUE TITLE
No sortBy function available

### ISSUE THREAD

**Issue by bltavares** [leisim/superpower#1]
Hi,

Thanks for starting this package. I definitely miss some of Kotlin's nice functions.
I've found this package when searching for `sortBy` on Dart Pub, but when I got to use it, there was no such function available.

The README has an example, but I can't find where the `sortBy` is implemented on the library.
Is the example there correct, or am I missing something?

Thanks

**Comment by simc** [comment]
Hey,
Thanks for the info. The method is actually called `sortedBy`.
I will fix the docs in the next version 👍

**Comment by simc** [comment]
The new version is now published ;)
